name: Install clang-format and clang-tidy
description: Install all clang tools.


inputs:
  os:
    description: Runner OS (e.g. ubuntu-latest or macos-latest).
    required: true
  version:
    description: The version of clang tools to install.
    required: true

runs:
  using: composite
  steps:

    - name: Install clang tools (macOS)
      if: inputs.os == 'macos-latest'
      shell: bash
      run: |
        set -euxo pipefail
        brew install llvm@${{ inputs.version }}
        brew link --force llvm@${{ inputs.version }}

    - name: Install clang tools (Ubuntu)
      if: inputs.os == 'ubuntu-latest'
      shell: bash
      run: |
        set -euxo pipefail
        curl -LSSf https://apt.llvm.org/llvm.sh |sudo bash -s -- "${{ inputs.version }}" all
        sudo update-alternatives --install /usr/bin/clang-format clang-format "/usr/bin/clang-format-${{ inputs.version }}" 999
        sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy "/usr/bin/clang-tidy-${{ inputs.version }}" 999

    - name: Confirm installed
      shell: bash
      run: |
        set -euxo pipefail
        clang-format --version
        clang-tidy --version
