name: Setup Dependencies
description: Setup project dependencies.


runs:
  using: composite
  steps:

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y cmake

    - name: Install Vita SDK
      uses: ./.github/actions/vitasdk

    - name: Install clang tools
      uses: ./.github/actions/clang
      with:
        version: "22"
