name: Install Vita SDK
description: Install the Vita SDK and its dependencies.


inputs:
  os:
    description: Runner OS (e.g. ubuntu-latest or macos-latest).
    required: true
  vitasdk-path:
    description: Destination directory where the Vita SDK will be installed.
    required: false
    default: ${{ runner.tool_cache }}/vitasdk


runs:
  using: composite
  steps:

    - name: Install dependencies (macOS)
      if: inputs.os == 'macos-latest'
      shell: bash
      env:
        ZSTD_VERSION: 1.5.7
      run: |
        set -euxo pipefail
        mkdir "$RUNNER_TEMP/zstd" && cd "$_"
        curl -sSL "https://github.com/facebook/zstd/releases/download/v$ZSTD_VERSION/zstd-$ZSTD_VERSION.tar.gz" |tar -xz
        cd "zstd-$ZSTD_VERSION"
        CFLAGS="-arch x86_64" LDFLAGS="-arch x86_64" arch -x86_64 make lib
        sudo mkdir -p /usr/local/opt/zstd/lib
        sudo cp "lib/libzstd.$ZSTD_VERSION.dylib" /usr/local/opt/zstd/lib/
        sudo ln -s "libzstd.$ZSTD_VERSION.dylib" /usr/local/opt/zstd/lib/libzstd.1.dylib

    - name: Add persistent VITASDK to ENV and PATH
      shell: bash
      run: |
        set -euxo pipefail
        echo "VITASDK=${{ inputs.vitasdk-path }}" >> "$GITHUB_ENV"
        echo "${{ inputs.vitasdk-path }}/bin" >> "$GITHUB_PATH"

    - name: INVESTIGATE
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        set -euxo pipefail
        wget -d -S -O - "https://github.com/vitasdk/vita-headers/raw/master/.travis.d/last_built_toolchain.py" || true
        install -m0600 /dev/stdin ~/.wgetrc <<< "header = Authorization: Bearer $GITHUB_TOKEN"
        wget -d -S -O - "https://github.com/vitasdk/vita-headers/raw/master/.travis.d/last_built_toolchain.py"

    - name: Install the Vita SDK
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        set -euxo pipefail
        install -m0600 /dev/stdin ~/.wgetrc <<< "header = Authorization: Bearer $GITHUB_TOKEN"
        git -C "$RUNNER_TEMP" clone --depth 1 "https://github.com/vitasdk/vdpm"
        cd "$RUNNER_TEMP/vdpm"
        bash -exo pipefail ./bootstrap-vitasdk.sh
        bash -exo pipefail ./install-all.sh
        cd .. && rm -rf vdpm
