name: CI

on:
  pull_request:
  push:

jobs:
  TestLintBuild:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Test
        run: echo TODO

      - name: Lint
        run: echo TODO

      - name: Build release
        run: |
          set -eux
          cmake -B build-release -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="${VITASDK}/share/vita.toolchain.cmake" -DCMAKE_POLICY_VERSION_MINIMUM=3.5 .
          cmake --build build-release

      # - name: Build Debug

      - name: Upload release artifact
        uses: actions/upload-artifact@v7
        with:
          name: release
          path: build-release/deplayenabler.suprx
          if-no-files-found: error

      # - name: Upload debug artifact
