name: CI

on:
  pull_request:
  push:

jobs:
  BuildTestLint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Install Vita SDK
        uses: ./.github/actions/vitasdk

      - name: Install clang tools
        uses: ./.github/actions/clang
        with:
          version: "22"

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Lint
        run: make lint

      - name: Upload release artifact
        uses: actions/upload-artifact@v7
        with:
          name: release
          path: build-release/*.s?prx
          if-no-files-found: error

      - name: Upload debug artifact
        uses: actions/upload-artifact@v7
        with:
          name: debug
          path: build-debug/*.s?prx
          if-no-files-found: error
