name: CI

on:
  pull_request:
  push:

jobs:
  BuildTestLint:
    strategy:
      matrix:
        os: [&artifact_os ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Install Vita SDK
        uses: ./.github/actions/vitasdk
        timeout-minutes: 10

      - name: Install clang tools
        uses: ./.github/actions/clang
        with:
          version: "22"

      - name: Copy TODO
        run: |
          set -euxo pipefail
          cp -vr vendor/quickmenureborn/quickmenureborn "$VITASDK/arm-vita-eabi/include/"
          cp -vr vendor/quickmenureborn/vitasdk_stubs/* "$VITASDK/arm-vita-eabi/lib/"
          find "$VITASDK" -type f

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Lint
        run: make lint

      - name: Upload release artifact
        env:
          artifact_os: *artifact_os
        if: matrix.os == env.artifact_os
        uses: actions/upload-artifact@v7
        with:
          name: release
          path: build-release/*.s?prx
          if-no-files-found: error

      - name: Upload debug artifact
        env:
          artifact_os: *artifact_os
        if: matrix.os == env.artifact_os
        uses: actions/upload-artifact@v7
        with:
          name: debug
          path: build-debug/*.s?prx
          if-no-files-found: error
